version: "3.7"
services:

  app:
    image: node:latest
    container_name: app
    tty: true

  db:
    image: postgres:latest
    container_name: db
    tty: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"


